fixed packagrs mor

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,7 +17,7 @@ if uname -m | grep -q 'arm' ;then
   error "Pi-Apps x86 is not not supported on arm processors. Get this instead https://github.com/Botspot/pi-apps."
 fi
 
-sudo apt update || error "The command 'sudo apt update' failed. Before Pi-Apps x86 will work, you must fix your apt package-management system."
+sudo apt --allow-unauthenticated update || error "The command 'sudo apt update' failed. Before Pi-Apps x86 will work, you must fix your apt package-management system."
 
 #install yad automatically
 if ! command -v yad >/dev/null;then
@@ -44,7 +44,7 @@ if [ -z "$DIRECTORY" ] || [ "$DIRECTORY" == "$HOME" ] || [ "$DIRECTORY" == bash 
   #if directory does not exist, download it
   if [ ! -d "$DIRECTORY" ];then
     echo "Downloading Pi-Apps x86..."
-    output="$(git clone --depth 1 https://github.com/MCRaspRBX/pi-apps-x86 "$DIRECTORY" 2>&1)"
+    output="$(git clone --depth 1 https://github.com/PythonScratcher/pi-apps-x86 "$DIRECTORY" 2>&1)"
     if [ ! -d "$DIRECTORY" ];then
       error "Pi-Apps-x86 download failed!\ngit clone output was: $output"
     fi
